core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda r: redirect('todos:index'), name='root'),
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path

from . import views as v


app_name = 'todos'
urlpatterns = [
    path('', v.index, name='index'),
    path('new/', v.new, name='new'),
    path('<int:pk>/', v.show, name='show'),
    path('<int:pk>/edit/', v.edit, name='edit'),
    path('<int:pk>/delete/', v.delete, name='delete'),
]

todos/models.py
from django.db import models


class Todo(models.Model):
    title = models.CharField('標題', max_length=150)
    content = models.TextField('內容')
    finish = models.BooleanField('已完成', default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.title

core/forms.py
from django.forms import Form, BooleanField


class DeleteCheckForm(Form):
    checked = BooleanField(label='確定要刪除嗎？')

todos/forms.py
from django.forms import ModelForm

from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        exclude = ('finish',)


class TodoEditForm(ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages as m

from core.forms import DeleteCheckForm

from .models import Todo
from .forms import TodoForm, TodoEditForm


def index(request):
    todos = Todo.objects.all()
    return render(request, 'todos/index.html', dict(todos=todos))


def new(request):
    form = TodoForm(request.POST or None)
    if form.is_valid():
        form.save()
        m.success(request, '新增成功！')
        return redirect('todos:index')

    return render(request, 'todos/new.html', dict(form=form))


def show(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    return render(request, 'todos/show.html', dict(todo=todo))


def edit(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoEditForm(request.POST or None, instance=todo)
    if form.is_valid():
        form.save()
        m.success(request, '更新成功！')
        return redirect('todos:index')

    return render(request, 'todos/edit.html', dict(form=form))


def delete(request, pk):
    form = DeleteCheckForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['checked']:
        print(form.cleaned_data['checked'])
        todo = get_object_or_404(Todo, pk=pk)
        todo.delete()
        m.success(request, '刪除成功！')
        return redirect('todos:index')

    return render(request, 'todos/delete.html', dict(form=form))

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>TODO List</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <style>
    textarea {
      resize: none
    }
  </style>
</head>

<body>
  {% load bootstrap4 %}

  <div class="container my-3">
    {% bootstrap_messages %}
    {% block body %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>

</html>

templates/shared/_form.html
{% load bootstrap4 %}
<form action="" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-outline-info float-right">
      送出
    </button>
  {% endbuttons %}
</form>

templates/todos/delete.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <h1>刪除確認</h1>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/todos/edit.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <h1>TODO 新增</h1>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/todos/index.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <a href="{% url 'todos:new' %}" class="btn btn-outline-success float-right">新增</a>
      <h1>TODO List</h1>
      <hr>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">標題</th>
            <th scope="col">狀態</th>
            <th scope="col">連結</th>
          </tr>
        </thead>
        <tbody>
          {% for todo in todos %}
            <tr>
              <th scope="row">{{ todo.pk }}</th>
              <td>{{ todo.title }}</td>
              <td>{{ todo.finish | yesno:'已完成,未完成' }}</td>
              <td><a href="{% url 'todos:show' todo.pk %}">檢視</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/todos/new.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <h1>TODO 新增</h1>
      <hr>
      {% include 'shared/_form.html' %}
    </div>
  </div>
{% endblock %}

templates/todos/show.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col">
      <a class="btn" href="{% url 'todos:index'%}">＜ 返回</a>
      <div class="card mt-3">
        <div class="card-body">
          <h1 class="card-title">#{{ todo.pk }} {{ todo.title }}</h1>
          <h6 class="card-subtitle mb-2 text-muted">{{ todo.finish | yesno:'已完成,未完成' }}</h6>
          <hr>
          <p class="card-text">
            {{ todo.content | linebreaks }}
          </p>
          <p class="text-right">
            建立時間：{{ todo.created_at }}<br>
            最後更新時間：{{ todo.updated_at }}
          </p>
          <hr>
          <a href="{% url 'todos:edit' todo.pk %}" class="card-link text-info">編輯</a>
          <a href="{% url 'todos:delete' todo.pk %}" class="card-link text-danger">刪除</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}